[package]
name = "snake_game"
version = "0.1.0"
edition = "2021"
authors = ["Bonington <yikun.chen@163.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"
piston_window = "*"